name: fastapi

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: install npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install serverless
        run: npm install -g serverless
        

      - name: Install Plugin and Deploy
        run: |
          serverless plugin install --name serverless-dotenv-plugin
          serverless plugin install --name serverless-python-requirements
          serverless deploy --stage dev

 

   


              
    
